### PR TITLE
dockerfiles: switch to using docker buildx bake

### PR DESCRIPTION
**Pull request by WanzenBug**
Using buildx bake, we can unify our build processes, no longer needing ad-hoc loops in makefiles. This also means docker will properly cache the different drbd9-* image stages, as we build for 9.1 and 9.2 versions in parallel, only diverging when we actually download the drbd package.

### CODE REVIEW

**Comment by WanzenBug** [comment]
Apparently still unstable :/

**Review by rck — APPROVED** [review]
guess it depends a bit what one considers more idiomatic: horrible Makefiles which I do know and love :) or some new "language" I don't know. but I see the benefit, good work.

I think https://github.com/piraeusdatastore/piraeus/pull/187/commits/e3c5ad6a30e21231c85d1c934222f91c68cf7d07 needs more explanation in the commit message why splitting the cache was necessary/what breaks otherwise

**Comment by WanzenBug** [comment]
> I think https://github.com/piraeusdatastore/piraeus/commit/e3c5ad6a30e21231c85d1c934222f91c68cf7d07 needs more explanation in the commit message why splitting the cache was necessary/what breaks otherwise

done

**Review by rck — APPROVED** [review]
LGTM

**Pull request merged**
