### PR TITLE
kmod-injector: add ubuntu-focal image

### PR DESCRIPTION
**Pull request by WanzenBug**
Fixes https://github.com/piraeusdatastore/piraeus-operator/issues/129

### CODE REVIEW

**Comment by rck** [comment]
weird enough I have it in my local checkout, but obviously it never made it into a commit.

thanks!

**Comment by WanzenBug** [comment]
@rck the push for quay.io failed, I guess the the account can't create the repo

**Comment by rck** [comment]
@WanzenBug should be created now with the correct perms

**Comment by fairEnough83** [comment]
Thanks

**Pull request merged**
