### PR TITLE
enable multi-arch build for -reactor and -injector

### PR DESCRIPTION
**Pull request by toelke**
See #74

I changed the `Makefile`s to build for the local architecture on `make update` and build for all specified architectures on `make upload`.

### CODE REVIEW

**Comment by rck** [comment]
LGTM. As we are not in a rush I guess and with Moritz being the one that oversees the CI parts, I'd wait for him being back from vacation to actually hit the merge button. Guess it is fair to ping him next Tue.

**Review by WanzenBug — CHANGES_REQUESTED** [review]
Over all: looks good and I suspect it's working.

Any particular reason we need to use `linux/arm64/v8` instead of just `linux/arm64`, like in the other PRs? 

Also, it would be nice to re-use the same workflows as piraeus-client&piraeus-server. I understand that this is a bit harder for drbd-loader, since we have multiple dockerfiles for one "product". However, drbd-reactor should work 1:1 the same as piraeus-server?

**Comment by toelke** [comment]
For the multiple `Dockerfile`s it seems as if we would need to have multiple `build`-blocks in the yaml; I'm not sure if that's nicer than having the loop in the `Makefile`.

What do you think?

**Comment by WanzenBug** [comment]
I'd say: "good enough" :wink: 

LGTM

**Review by WanzenBug — APPROVED** [review]

**Comment by WanzenBug** [comment]
Apparently not: https://github.com/piraeusdatastore/piraeus/runs/3463516323 :disappointed:

**Comment by rck** [comment]
just some thoughts on where the complexity should be: In general I'd like to see it (hidden) in the `Makefile`s if possible. They should be easy to use if necessary. Necessary for whatever reason: Somebody just wants a quick rebuild on the command line, or a quick test build. Or switches to another CI pipeline. Maybe one in house. Besides the other points to me it always has a certain degree of vendor lock-in vibes.

**Pull request merged**
